# Generated by Django 5.1.3 on 2024-11-19 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
